language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

before_install:
  - npm install codecov
  - npm install react
  - npm install prop-types

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov
